# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      AZURE_WEBAPP_NAME: cartestapp    # set this to your application's name
      AZURE_WEBAPP_PACKAGE_PATH: '.' 
      

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    - name: Restore dependencies
      run: dotnet restore --interactive
      working-directory: CarBackEnd
    - name: Build
      run: dotnet build --configuration Release
      working-directory: CarBackEnd/CarBackEnd
    - name: Test
      run: dotnet test --verbosity normal 
      working-directory: CarBackEnd/Car.Tests
  sonarscan:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
     #SonarScan
    - name: SonarScanner for .NET Core with pull request decoration support
      uses: highbyte/sonarscan-dotnet@2.0
      with:
        # The key of the SonarQube project
        sonarProjectKey: ita-social-projects_Car-Back-End
        # The name of the SonarQube project
        sonarProjectName:  Car-Back-End
        # The name of the SonarQube organization in SonarCloud. For hosted SonarQube, skip this setting.
        sonarOrganization: ita-social-projects
        sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="/github/workspace/CarBackEnd/Car.Tests/coverage.opencover.xml" /d:sonar.coverage.exclusions=**/Car.DAL/**,**/Car.BLL/Dto/**,**/Startup.cs,**/Program.cs /d:sonar.exclusions=**/Car.DAL/Migrations/**
        dotnetBuildArguments: ./CarBackEnd/CarBackEnd.sln -c Debug
        dotnetTestArguments: ./CarBackEnd/Car.Tests/Car.Tests.csproj --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover 
  
  delivery_to_azure:
      needs: [build]
      runs-on: windows-latest

      steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.102
      - name: Restore dependencies
        run: nuget restore 
        working-directory: CarBackEnd
      - name: Build
        run: dotnet build -c Release
        working-directory: CarBackEnd/CarBackEnd
  #    - name: Run for check
  #     run: dotnet run -c Debug
  #     working-directory: CarBackEnd/CarBackEnd
      - name: dotnet publish
        run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}' --no-restore --no-build
  #      run: dotnet publish 
        working-directory: CarBackEnd/CarBackEnd  
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
           app-name: ${{ env.AZURE_WEBAPP_NAME }} 
           publish-profile: ${{ secrets.PUBLISH_PROFILE  }} 
           package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
