name: CD
on:
  push:
    branches: [ develop ]

defaults:
  run:
    shell: bash
    working-directory: Car.Backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "appsettings.Development.json"
          json: ${{ secrets.APP_DEV }}
          dir: './Car.Backend/Car.WebApi'

      - name: create-json
        id: create-json2
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "appsettings.json"
          json: ${{ secrets.APP }}
          dir: './Car.Backend/Car.WebApi'

      - name: create-json
        id: create-json3
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "appsettings.Production.json"
          json: ${{ secrets.APP_PROD }}
          dir: './Car.Backend/Car.WebApi'

      - name: create-json
        id: create-json4
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "credential-firebase.json"
          json: ${{ secrets.FIREBASE }}
          dir: './Car.Backend/Car.WebApi/wwwroot/Credentials/'

      - name: login to docker
        run: |
          docker login --username ${{secrets.DOCKER_USER}} --password ${{secrets.DOCKER_PASSWORD}}

      - name: docker build
        run: |
          docker build -t car_api .

      - run: |
          docker image ls

      - name: push to DockerHub
        run : |
          docker tag car_api:latest ${{secrets.DOCKER_REPO}}
          docker push ${{secrets.DOCKER_REPO}}
